import NextHead from "next/head";

const Head = () => {
    return (
        <NextHead>
        <title>imported head</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@HeadStackHQ" />
        <meta name="twitter:title" content='Marilyn home page' />
        <meta name="twitter:description" content="Marilyn description" />
        <meta
          name="twitter:image"
          content="https://images.unsplash.com/photo-1684670179697-7b6d0213f152?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
        />
        <meta
          property="twitter:image"
          content="https://images.unsplash.com/photo-1684670179697-7b6d0213f152?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
        />
      </NextHead>
    )
}

export default Head